name-template: '$NEXT_PATCH_VERSION '
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    label: 'kind/feature'
  - title: 'Bug Fixes'
    label: 'kind/bug'
  - title: 'Maintenance'
    label: 'chore'
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## What's Changed

  $CHANGES
